version: '3.8'

services:
  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Booking.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Username=postgres;Password=${DB_PASSWORD};Database=Booking_Db
    depends_on:
      - postgres-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Booking_Db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
volumes:
  pgdata:
